### ISSUE TITLE
where get the certs and key file for the flask server

### ISSUE THREAD

**Issue by Netonline2016** [fleeto/flaskapp#2]
hi, i referenced the demo from the 《深入浅出 Istio》7.9.2.
but i didn't the certs and key file for the flask server.
i want to know where can i get them. thanks.

**Comment by fleeto** [comment]
I'm using my own cert in this book. Its generated for my domain name by [Let's Encrypt](https://letsencrypt.org/), you can create yours on this site.

**Comment by Netonline2016** [comment]
@fleeto 
thanks for your reply.
the issue had closed.
